server:
  port: 12000

spring:
  datasource:
    url: jdbc:mysql://69.171.71.251:3306/mydb
    username: admin
    password: qgJX59pQln8Q7lhgw7CN
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB





