server:
  port: 12000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyDB
    username: root
    password: 123456
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false




